try {
  console.log('try');

  //....
} catch (err) {
  console.error(err);
} finally {
}
